// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "DIRuntime",
    platforms: [.macOS(.v13)],
    products: [.library(name: "DIRuntime", targets: ["DIRuntime"])],
    targets: [
        .target(
            name: "DIRuntime",
            path: "di-project",
            exclude: [
                "Application/AppDelegate.swift",
                "Application/Scene/AppCoordinator.swift",
                "Application/Scene/AuthorizedApplicationContext.swift",
                "Application/Scene/WindowController.swift",
                "Application/SceneDelegate.swift",
                "Assets.xcassets",
                "Base.lproj",
                "DependencyInjection/AccountFactory.swift",
                "DependencyInjection/DIContainer.swift",
                "Features/Home/HomeCoordinator.swift",
                "Features/Home/HomeDIContainer.swift",
                "Features/Home/HomeDetailViewController.swift",
                "Features/Home/HomeDraftState.swift",
                "Features/Home/HomeListViewController.swift",
                "Features/Login/LoginViewController.swift",
                "Features/Settings/AppearanceViewController.swift",
                "Features/Settings/SettingCoordinator.swift",
                "Features/Settings/SettingDIContainer.swift",
                "Features/Settings/SettingsViewController.swift",
                "Info.plist",
                "Navigation/NavigationController.swift",
                "Navigation/RootController.swift",
                "Navigation/SplitViewController.swift",
                "Navigation/TabBarController.swift",
                "Platform/ApplicationBindings.swift",
                "Platform/SceneBindings.swift",
                "Platform/SystemPolicyObserver.swift",
                "Presentation/ScenePresentationEnvironment.swift",
                "Services/Animation/AnimationEngine.swift",
                "Services/Animation/AnimationHost.swift",
                "Services/Media/MediaOverlayCoordinator.swift",
                "Shared/MessageViewController.swift"
            ],
            sources: [
                "Account/AccountAnimationCacheProvider.swift",
                "Account/AccountConfiguration.swift",
                "Account/AccountLifetime.swift",
                "Account/AccountPurchaseService.swift",
                "Account/AccountRepository.swift",
                "Account/AccountStore.swift",
                "Account/AuthenticatedAccount.swift",
                "Account/SessionManager.swift",
                "Account/UserContext.swift",
                "Account/UserContextImpl.swift",
                "Application/Launch/LaunchController.swift",
                "Application/Launch/LaunchControllerImpl.swift",
                "Application/Launch/LaunchControllerState.swift",
                "Application/Routing/AppRoute.swift",
                "Application/Routing/ApplicationEventRouter.swift",
                "Application/Routing/ExternalRequest.swift",
                "Application/Runtime/ApplicationState.swift",
                "Application/Runtime/SharedApplicationContext.swift",
                "Features/Home/HomeItem.swift",
                "Presentation/PresentationConfig.swift",
                "Presentation/PresentationConfigStore.swift",
                "Services/Activity/ApplicationActivity.swift",
                "Services/Activity/WakeupManager.swift",
                "Services/Advertising/AdPlacement.swift",
                "Services/Advertising/AdsManager.swift",
                "Services/Downloads/DownloadedMediaStoreManager.swift",
                "Services/Downloads/FetchManager.swift",
                "Services/Downloads/PrefetchManager.swift",
                "Services/Media/MediaManager.swift",
                "Services/Notifications/PushRegistrationService.swift",
                "Services/Purchases/IAPManager.swift",
                "Services/Purchases/VerifiedPurchase.swift",
                "Services/Security/AppLockService.swift",
                "Shared/FeatureConfiguration.swift",
                "Shared/NetworkArguments.swift",
                "Shared/ObservableState.swift",
                "Shared/RuntimeError.swift"
            ]
        ),
        .testTarget(name: "DIRuntimeTests", dependencies: ["DIRuntime"], path: "Tests")
    ],
    swiftLanguageModes: [.v5]
)
